version: '3'
services:
  app:
    build: .
    ports:
    - "8004:8004"
    #read_only: true
    shm_size: 256m
    stdin_open: true
    tty: true
    networks:
      envoymesh:
        aliases:
          - app
networks:
  envoymesh: {}